# Generated by Django 3.2.16 on 2023-01-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagRecipe',
        ),
    ]
