# Generated by Django 3.2.16 on 2023-01-17 18:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usershoppingcartrecipes',
            unique_together={('recipe', 'user')},
        ),
    ]
