# Generated by Django 3.2.16 on 2023-01-10 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingridientrecipe_recipe_tagrecipe_userfavoriterecipes_usershoppingcartrecipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
