# Generated by Django 3.2.16 on 2023-01-12 19:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavoriterecipes',
            unique_together={('recipe', 'user')},
        ),
    ]
