# Generated by Django 3.2.16 on 2023-01-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=10, unique=True, verbose_name='Цвет тега'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug-тега'),
        ),
        migrations.AlterUniqueTogether(
            name='ingridientrecipe',
            unique_together={('ingridient', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'slug')},
        ),
    ]
