# Generated by Django 3.2.16 on 2023-01-13 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230113_2250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingridient',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingridientrecipe',
            options={'verbose_name': 'Ингридиент в рецепте', 'verbose_name_plural': 'Ингридиенты в рецептах'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'verbose_name': 'Тег рецепта', 'verbose_name_plural': 'Теги рецептов'},
        ),
        migrations.AlterModelOptions(
            name='userfavoriterecipes',
            options={'verbose_name': 'Рецепт в избранном', 'verbose_name_plural': 'Рецепты в избранном'},
        ),
        migrations.AlterModelOptions(
            name='usershoppingcartrecipes',
            options={'verbose_name': 'Рецепт в корзине', 'verbose_name_plural': 'Рецепты в корзине'},
        ),
    ]
