# Generated by Django 3.2.16 on 2023-01-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20230114_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingridient',
            name='amount',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
