# Generated by Django 3.2.16 on 2023-01-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_ingridient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingridient',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingridientrecipe',
            name='amount',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
