# Generated by Django 3.2.16 on 2023-01-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subcribe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribe',
            new_name='Subscribe',
        ),
    ]
