# Generated by Django 3.2.16 on 2023-01-08 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_subcribe_subscribe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('follower', 'following')},
        ),
    ]
