# Generated by Django 3.2.16 on 2023-01-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230114_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='user',
            new_name='follower',
        ),
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('follower', 'following')},
        ),
    ]
